#!/usr/bin/env bash
# The kit's own gate. Every check runs from a file, never inline, because inline quoting
# produced three false failures while this was being built.
cd "$(dirname "$0")/.." || exit 1
# Bytecode caches are regenerated by every python run and are gitignored. Clear them first so
# they cannot register as a leak they will never actually ship as.
find . -name __pycache__ -type d -not -path "./.git/*" -exec rm -rf {} + 2>/dev/null
G=/usr/bin/grep; pass=0; fail=0
chk(){ if [ "$2" -eq 0 ]; then echo "  PASS  $1"; pass=$((pass+1)); else echo "  FAIL  $1 ($2)"; fail=$((fail+1)); fi; }

control=$($G -ril mission . --exclude-dir=.git | wc -l | tr -d ' ')
[ "$control" -gt 0 ] || { echo "ABORT: grep found nothing for a term known to exist. Every null below would be meaningless."; exit 1; }
echo "  control: grep works ($control files match a known term)"

# The denylist lives in tools/.denylist, which is gitignored on purpose: it names the author's
# private systems, so shipping it would itself be the leak it exists to prevent. Without the file
# the sanitization sweep is skipped and says so, rather than silently passing.
if [ -f tools/.denylist ]; then
  while IFS= read -r t; do
    [ -z "$t" ] && continue
    chk "no leak: $t" "$($G -ril "$t" . --exclude-dir=.git --exclude-dir=tools --exclude-dir=__pycache__ 2>/dev/null | wc -l | tr -d ' ')"
  done < tools/.denylist
else
  echo "  SKIP  sanitization sweep (tools/.denylist absent, this is expected for anyone but the author)"
fi
chk "no absolute home paths" "$($G -rn "/Users/" . --exclude-dir=.git --exclude-dir=tools --exclude-dir=__pycache__ 2>/dev/null | wc -l | tr -d ' ')"
chk "zero em dashes" "$($G -rl $'—' . --exclude-dir=.git --exclude-dir=tools --exclude-dir=__pycache__ 2>/dev/null | wc -l | tr -d ' ')"

python3 tools/check-structure.py; chk "structure" $?
python3 tools/mutation-sweep.py >/dev/null 2>&1; chk "gates discriminate (mutation sweep)" $?
python3 tools/eval-router.py >/dev/null 2>&1; chk "router eval >=85% top-1" $?
python3 tools/build-cheatsheet.py >/dev/null 2>&1; chk "cheat sheet regenerates" $?

printf '%s' '{"tool_input":{"command":"rm -rf /"}}' | plugins/exec/hooks/guard-destructive.sh >/dev/null 2>&1
[ $? -eq 2 ]; chk "guard blocks a destructive command" $?
printf '%s' '{"tool_input":{"command":"ls -la"}}' | plugins/exec/hooks/guard-destructive.sh >/dev/null 2>&1
chk "guard allows a safe command" $?
printf '%s' '{"prompt":null}' | python3 plugins/exec/hooks/router.py >/dev/null 2>&1
chk "router fails open on bad input" $?

echo; echo "  PASS: $pass   FAIL: $fail"
[ "$fail" -eq 0 ]
